version: '2'

services:
  web:
    image: cmcdev/web:2.4.0
    ports:
      - 3000:3000
      # - 3001:3001
    volumes:
      - .:/www/web/
    working_dir: /www/web
    entrypoint: sh /www/start.sh
    stdin_open: true
    tty: true